# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 300)
        MainWindow.setMinimumSize(QtCore.QSize(735, 300))
        MainWindow.setMaximumSize(QtCore.QSize(735, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -10, 731, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 80, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lvl_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lvl_number.setGeometry(QtCore.QRect(440, 90, 141, 21))
        self.lvl_number.setObjectName("lvl_number")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lvl1_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lvl1_number.setGeometry(QtCore.QRect(440, 130, 141, 21))
        self.lvl1_number.setObjectName("lvl1_number")
        self.req_rune_label = QtWidgets.QLabel(self.centralwidget)
        self.req_rune_label.setGeometry(QtCore.QRect(100, 170, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.req_rune_label.setFont(font)
        self.req_rune_label.setObjectName("req_rune_label")
        self.req_rune_number = QtWidgets.QLabel(self.centralwidget)
        self.req_rune_number.setGeometry(QtCore.QRect(440, 180, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.req_rune_number.setFont(font)
        self.req_rune_number.setObjectName("req_rune_number")
        self.calculate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_btn.setGeometry(QtCore.QRect(10, 220, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.calculate_btn.setFont(font)
        self.calculate_btn.setObjectName("calculate_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.calculate_btn.clicked.connect(self.Click)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)






    def Click(self):
        self.lvl1 = int(self.lvl1_number.text())
        
        self.lvl = int(self.lvl_number.text())
        
        total_rune_cost = 0
        
        for i in range(self.lvl1):
            
            total_rune_cost += self.Calculate_Rune()
            self.lvl += 1
            
        self.req_rune_label.setText("The Required Rune is:")
        self.req_rune_number.setText(str(math.ceil(total_rune_cost)))
        
    def Calculate_Rune(self):
        if ((self.lvl + 81) - 92) * 0.02 < 0:
            x = 0
        else:
            x = ((self.lvl + 81) - 92) * 0.02
        
        Rune_Cost = math.floor(((x + 0.1) * ((self.lvl+81) ** 2)) + 1)

        return Rune_Cost

    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ELDEN RING RUNE CALCULATOR"))
        self.label_2.setText(_translate("MainWindow", "Your Level"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Number of Levels to Upgrade</p></body></html>"))
        #self.req_rune_label.setText(_translate("MainWindow", "The Required Rune is:"))
        #self.req_rune_number.setText(_translate("MainWindow", "99999999"))
        self.calculate_btn.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
